### ISSUE TITLE
Archlinux PKGBUILD

### ISSUE THREAD

**Issue by y0uCeF** [harishnkr/bsol#1]
Here is my PKGBUILD for use in Archlinux and its derivatives. It may be added to [AUR](https://aur.archlinux.org/)
**PKGBUILD**
```
pkgname=grub-theme-bsol-git
pkgver=0+7.g998cb90
pkgrel=1
pkgdesc="Grub2 blue-screen-of-life theme"
url=https://github.com/harishnkr/bsol
arch=('any')
license=('GPL')
depends=()
makedepends=('git')
source=('git+https://github.com/harishnkr/bsol')
md5sums=('SKIP')
install=grub-bsol-theme.install

pkgver() {
    cd bsol
    echo "0+$(git rev-list --all | wc -l).g$(git rev-parse --short HEAD)"
}

package() {
    cd bsol
    install -v -Dm644 -t "$pkgdir/usr/share/licenses/${pkgname}" \
        LICENSE
    cd bsol
    install -v -Dm644 -t "$pkgdir/boot/grub/themes/bsol" \
        *.png
    install -v -Dm644 -t "$pkgdir/boot/grub/themes/bsol" \
        *.pf2
    install -v -Dm644 -t "$pkgdir/boot/grub/themes/bsol" \
        theme.txt
    install -v -Dm644 -t "$pkgdir/boot/grub/themes/bsol" \
        icons/*.png

}
```
**grub-bsol-theme.install**
```
#!/bin/sh

post_install() {
    echo ":: To use the theme:"
    echo "   1. Set GRUB_THEME in /etc/default/grub to /boot/grub/themes/bsol/theme.txt"
    echo "   2. Regenerate your GRUB configuration"
    echo "      e.g. grub-mkconfig -o /boot/grub/grub.cfg"
}

post_upgrade() {
    echo ":: To complete the upgrade, you must re-install the theme using"
    echo "   grub-install and grub-config."
}
```

**Comment by harishnkr** [comment]
The package build seem solid. I think you can upload it to AUR if you want to since the maintainer need not be the creator. I am yet to try this out. In case I am confident in the PKGBUILD (which I believe would be working fine) I will upload it after testing.

**Comment by harishnkr** [comment]
I have added the AUR package. There were a few changes to the script but nevertheless thanks for scripts.

Package live at https://aur.archlinux.org/packages/grub-theme-bsol-git

**Comment by y0uCeF** [comment]
It worked fine from AUR, thank you.
You may close it.

**Comment by harishnkr** [comment]
I feel like` grub-install  --theme=bsol`  fails to copy the icons folder. Could not figure out the problem. At the same time I dont want the PKGBUILD to copy files directly to the `/boot` directory.
