### ISSUE TITLE
Font change affects the grub terminal font

### ISSUE THREAD

**Issue by emmaexe** [harishnkr/bsol#2]
Not sure if this is intended or if there is a way to fix this but the custom font in the theme also applies to the grub terminal, and is not the greatest when it comes to readability.

**Comment by harishnkr** [comment]
I have updated the repo and added a regular font. Please change the line containing the terminal font from `Victor Mono Italic 20` to `Victor Mono Regular 16`. Let me know if you have any further problems.

**Comment by emmaexe** [comment]
Tried it out and it does fix the issue 👍

**Comment by harishnkr** [comment]
Glad to hear
