### ISSUE TITLE
grub-install: error: cannot find EFI directory

### ISSUE THREAD

**Issue by romarmph** [harishnkr/bsol#3]
I'm trying to install this grub them on arch. 
`sudo grub-install --themes=bsol`

Results to this:

Installing for x86_64-efi platform.
grub-install: error: cannot find EFI directory.

EDIT:

Installed it manually and went smoothly

**Comment by harishnkr** [comment]
Yeah something is wrong with the aur installation. Some resources are not present in the final directory. Hence I added the manual installation.
