### ISSUE TITLE
Installing instructions unclear for Fedora base systems

### ISSUE THREAD

**Issue by guefra** [harishnkr/bsol#5]
Hi there!

I really like your work, this GRUB theme is just perfection. The thing is, I currently use Nobara 40 (basically Fedora 40, just some inprovements) and wanted to install this theme. I first followed your instructions but it didn't work. Then I searched on the web and found solutions for Fedora that didn't work either. Lastly I looked into an installer script for a different GRUB theme and found out how to install the GRUB theme on Fedora 40 (Nobara 40 and probably some other versions) so maybe you could include those steps to make it easier for other users:

1. Go to the location you cloned the repo (e.g. you cloned it to Downloads, `cd ~/Downloads/bsol`) 
2. Copy the folder _**bsol**_  to _**/usr/share/grub/themes**_ (if it isn't there use `mkdir /usr/share/grub/themes`) with the command `sudo cp -r bsol /usr/share/grub/themes`
3. Edit the file _**/etc/default/grub**_ with `sudo nano /etc/default/grub` (replace nano with your favorite editor or leave it) by
    - commenting the line _**GRUB_TERMINAL_OUTPUT="console"**_ by adding a _**#**_ to the front of it
    - adding the line _**GRUB_GFXMODE="[x_res]x[y_res]x32"**_ (change _**x_res**_ and _**y_res**_ to your screen resolution, e.g. 1920x1080)
    - adding the line _**GRUB_THEME="usr/share/grub/themes/bsol/theme.txt"**_
4. Reload your grub config with the command `sudo grub2-mkconfig -o /boot/grub2/grub.cfg` (when using BIOS) or `sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg` (when using UEFI)
5. Reboot your system and enjoy the best GRUB theme out there

PS: Maybe you also want to tell your users that they probably have to download the used font.

**Comment by harishnkr** [comment]
Hi @guefra and thanks for your feedback. I have added the Fedora specific instructions. However I would like to refrain from giving certain instructions since the basics must be known if you are tweaking the bootloader theme. There are chances that the whole boot process may crash with the wrong configuration so I would not like to provide the  documentation with those for those who have never tried it in the past or dont have the know how to revert from the initial crashes. 

I will add the lines with respect to change in resolution and the line where the output is given as console in the troubleshooting section. 

I appreciate your concern you give for others and I truly appreciate your advice.

Closing the issue. If you would like to update the troubleshooting section, please do create a pull request section.

**Comment by racka98** [comment]
I just tried installing this theme on Fedora 40 with no success from the suggested solution by @guefra 

The actual step that worked for me were.

1. Copy the entire `bsol/` directory to `/boot/grub2/themes/`. There will be no `grub` just `grub2` if you are on Grub2.
2. Edit the file `/etc/default/grub` with `sudo vi /etc/default/grub` (replace vi with your favorite editor or leave it)
   - Edit the line `GRUB_TERMINAL_OUTPUT="console"` to  `GRUB_TERMINAL_OUTPUT="gfxterm"`, don't comment it out
   - Edit the line `GRUB_ENABLE_BLSCFG` to `GRUB_ENABLE_BLSCFG="false"`
   - Save the file
3. Reload your grub config with the command `sudo grub2-mkconfig -o /boot/grub2/grub.cfg`. Doesn't matter if you are using UEFI or BIOS. Don't run the suggested `sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg`, it's not necessary and will likely break with next update if grub is touched by it. The file `/boot/efi/EFI/fedora/grub.cfg` just links to `/boot/grub2/grub.cfg` and it's not supposed to be touched as described by Fedora docs.
4. Reboot and enjoy your theme

Things to note;
- `GRUB_TERMINAL_OUTPUT="console"` shouldn't be removed, it should instead be  `GRUB_TERMINAL_OUTPUT="gfxterm"`
- Only run `sudo grub2-mkconfig -o /boot/grub2/grub.cfg` as recommended by Fedora docs.
- If you did touch  `/boot/efi/EFI/fedora/grub.cfg`, you can recover default file using `sudo dnf reinstall grub2-common grub2-efi\*` then you would proceed with the theme installation.

My  `/boot/efi/EFI/fedora/grub.cfg` contents
```
search --no-floppy --root-dev-only --fs-uuid --set=dev eb2012e0-decb-4285-9897-cd59627a2667
set prefix=($dev)/grub2
export $prefix
configfile $prefix/grub.cfg
```

My `/etc/default/grub` contents
```
GRUB_TIMEOUT="5"
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT="saved"
GRUB_DISABLE_SUBMENU="true"
GRUB_TERMINAL_OUTPUT="gfxterm"
GRUB_CMDLINE_LINUX="rhgb quiet"
GRUB_DISABLE_RECOVERY="true"
GRUB_ENABLE_BLSCFG="false"
GRUB_THEME="/boot/grub2/themes/bisol/theme.txt"

export GRUB_COLOR_NORMAL="light-gray/black"
export GRUB_COLOR_HIGHLIGHT="magenta/black"
```

**Comment by harishnkr** [comment]
Thanks for your feedback @racka98 . I would suggest since I dont use Fedora it would be helpful(and definitely better) if you could make the changes yourself as you deem fit, taking your time. In case you are not in a position to do so, do let me know.

**Comment by harishnkr** [comment]
PR #7 merged. Thank you so much @racka98.
Closing this issue for now.
