### ISSUE TITLE
There is no option for booting windows

### ISSUE THREAD

**Issue by Tataridayo** [harishnkr/bsol#6]
I recently installed windows on MacBook and after that I installed arch Linux. After I installed this theme I see an only Arch Linux boot option. I checked my drive to maybe I wiped off windows from my pc but it was still there.

**Comment by harishnkr** [comment]
I believe that you have not updated your grub boot entries. I guess you should use OS-Prober for updating them. Although I believe this is not exactly an issue with the theme, check out this link for more info...

https://wiki.archlinux.org/title/GRUB#Detecting_other_operating_systems

Closing the issue for now

**Comment by Tataridayo** [comment]
I should've searched more. Anyway, thank you for fixing my issue!
